name: EGRET Prescient CI

on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
         types: run-test

defaults:
    run:
        shell: bash -l {0}

jobs:
    build:
        name: Prescient main, ${{ matrix.os }}, Python ${{ matrix.python-version }}, Pyomo ${{ matrix.pyomo-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: [3.7]
                pyomo-version: [6.1.2]
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: test_env
              python-version:  ${{ matrix.python-version }}
              auto-activate-base: false
          - name: Conda Env
            run: |
              conda info
              conda list
          - name: Install CBC
            run: |
              if [ ${{ matrix.os }} = windows-latest ]
              then
                # download CBC binary, copy to place already in PATH
                curl -O https://ampl.com/dl/open/cbc/cbc-win64.zip
                unzip cbc-win64.zip
                cp cbc.exe $CONDA_PREFIX
              else
                conda install -c conda-forge coincbc
              fi
              # test cbc executable
              cbc -quit
          - name: Install Nose/Parameterized/Pytest
            run: |
              pip install nose parameterized pytest coveralls
          - name: Install Cython/Numpy/Pandas
            run: |
              pip install cython numpy pandas
          - name: Install Pyomo
            run: |
              pip install git+https://github.com/Pyomo/pyomo.git@${{ matrix.pyomo-version }}
          - name: Install Coramin
            run: |
              pip install coramin
          - name: Install EGRET
            run: |
              python setup.py develop
          - name: Install Prescient
            run: |
              cd ..
              git clone --depth=1 https://github.com/grid-parity-exchange/Prescient.git
              cd Prescient
              python setup.py develop
          - name: Run Prescient Tests
            run: |
              cd ../Prescient
              python tests/simulator_tests/test_sim_rts_mod.py
